Adding geneve support in p4_ovs
ipdk-io/ovs pull request #106
Opened 2024-01-21 12:38 UTC by satish153

Added tunnel_type field to identify tunnel type.

2024-01-23 20:39 UTC, ffoulkes requested changes
You need to sign your commits by specifying the `-s` parameter when you run `git commit`. Failure to do so results in a DCO error.

This needs to be done for every commit in the PR.

I believe you can fix this after the fact by doing the following:
```bash
git commit -s --amend
(:wq to save updated commit comment)
git push -f
```

2024-02-01 17:20 UTC, ffoulkes approved these changes
LGTM

2024-02-01 17:43 UTC, nupuruttarwar commented on include/openvswitch/ovs-p4rt.h
> +  VLAN_POP,
why are we considering VLAN_PUSH, VLAN_POP, NEIGHBOR, etc as p4_tunnel_type? Should this be only vxlan and geneve and similar to ovs_tunnel_type declared below? In OVS, I see following tunnel configs in one of the functions

    return (class->get_config == get_tunnel_config &&
            (!strcmp("geneve", type) || !strcmp("vxlan", type) ||
             !strcmp("lisp", type) || !strcmp("stt", type) ||
             !strcmp("gtpu", type) || !strcmp("bareudp",type)));
}

I understand we are supporting vxlan and geneve out of the above

2024-02-02 13:43 UTC, satish153 commented on include/openvswitch/ovs-p4rt.h
> +  VLAN_POP,
Thanks for noticing this.
These are actually mod profiles.
My initial logic was to have common action and different action params for each of mod profiles. So, I created this enum to map to mod profiles in the lnw.p4 program. Later, I had to change that logic, as mod action cannot be set runtime.
This enum is not needed anymore.

2024-02-02 17:51 UTC, 5abeel approved these changes
LGTM

2024-02-02 19:15 UTC, nupuruttarwar approved these changes
LGTM

2024-02-02 19:15 UTC, nupuruttarwar commented
@satish153 please sign off your commit for DCO check to pass

2024-02-03 09:56 UTC, merged