Modified p4ovs_test_runner.py : skip any blank line, delay between ex…
ipdk-io/ovs pull request #55
Opened 2022-08-24 04:32 UTC by dkaranjai

…ecution of pre_tests and test script and between consecutive test script runs

Signed-off-by: Dwaipayan Karanjai <dwaipayan.karanjai@intel.com>

2022-08-24 04:46 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/ef195d31af234a680e2e6f1a4e3be43b5a4f38bd

2022-08-24 04:48 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/ef195d31af234a680e2e6f1a4e3be43b5a4f38bd

2022-08-24 06:40 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/4ff83c885f4d2598b496fc27c2f61f3db9540e8e

2022-08-24 07:32 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-24 09:00 UTC, ipdksw commented
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-24 10:24 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-24 11:01 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-24 12:24 UTC, dkaranjai commented
Attaching the log from CI run:
[ptf_auto_consoleText.txt](https://github.com/ipdk-io/ovs/files/9415979/ptf_auto_consoleText.txt)

2022-08-25 17:30 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-26 08:35 UTC, ipdksw commented
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-26 14:32 UTC, 5abeel commented
General comment: Recommend using a title and description breakup of commit message. Currently, we have the title showing a long sentence that breaks and rest added in the description. Please avoid this in the future PRs

2022-08-26 14:33 UTC, 5abeel requested changes

2022-08-26 14:33 UTC, 5abeel commented on ptf_tests/p4ovs_test_runner.py
> +    sleep 2
This should be `time.sleep(2)`

2022-08-26 17:23 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-27 07:22 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-12/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-27 08:37 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-13/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-27 10:31 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-14/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/6595d95dc47725b3601c314d422a9eaab5a25d39

2022-08-29 03:55 UTC, dkaranjai commented on ptf_tests/p4ovs_test_runner.py
> +    sleep 2
this is in shell not pyrhon

2022-08-29 04:09 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-55-15/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/821c2b3b5f00c9dc9632a820f043f73bc365666b

2022-08-29 15:01 UTC, 5abeel approved these changes
lgtm

2022-08-30 02:50 UTC, dkaranjai commented
Can this be merged? We need one more approval for that.

2022-08-30 03:15 UTC, nupuruttarwar approved these changes
LGTM

2022-08-30 03:21 UTC, merged