Fix MTU config with TAP Script
ipdk-io/ovs pull request #63
Opened 2022-09-06 14:21 UTC by dpathrabe

Signed-off-by: dpathrabe <deepak.p.pathrabe@intel.com>

2022-09-06 14:50 UTC, ipdksw commented
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/dd3d5c8bc94d7adca801815f2f1ef0d382d9175f

2022-09-06 15:45 UTC, dpathrabe commented
[mtu_config_tap_fix_exec.log](https://github.com/ipdk-io/ovs/files/9498457/mtu_config_tap_fix_exec.log)
[mtu_config_tap_fix_build.log](https://github.com/ipdk-io/ovs/files/9498459/mtu_config_tap_fix_build.log)

Attaching build and execution logs 

Fix comment : Adding OSError exception to send_packet function call, which is an assertion in this scenario to test if packet sending is failed on account of MTU and packet size difference

2022-09-06 18:05 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/dd3d5c8bc94d7adca801815f2f1ef0d382d9175f

2022-09-07 04:49 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/92783a0fe4181f40e74c87a7e939abd86264b385

2022-09-09 05:24 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0d31ffbcdff03a1416bfa78c6a48a9a50e1208d2

2022-09-09 06:36 UTC, ipdksw commented
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-5/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0d31ffbcdff03a1416bfa78c6a48a9a50e1208d2

2022-09-13 04:21 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0d31ffbcdff03a1416bfa78c6a48a9a50e1208d2

2022-09-14 06:55 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0d31ffbcdff03a1416bfa78c6a48a9a50e1208d2

2022-09-15 07:06 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/0d31ffbcdff03a1416bfa78c6a48a9a50e1208d2

2022-09-15 07:28 UTC, dkaranjai requested changes

2022-09-15 07:28 UTC, dkaranjai commented on ptf_tests/tests/mtu_config_test_with_tap.py
> +           errstr = f"Message too long"
can remove the f

2022-09-15 08:23 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f6b019434d4303b6ebe2b9af1580a3bd5dc6bd42

2022-09-19 19:04 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/f6b019434d4303b6ebe2b9af1580a3bd5dc6bd42

2022-09-20 03:28 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-11/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/c7ad3ef530be619691a4ab2d0108ec8e08de8d16

2022-09-20 12:46 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-12/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/c7ad3ef530be619691a4ab2d0108ec8e08de8d16

2022-09-20 13:26 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-13/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/c7ad3ef530be619691a4ab2d0108ec8e08de8d16

2022-09-21 04:01 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-14/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/4f1bc06d1c25750cec49cbbcb3096bc92b91d3e7

2022-09-21 11:23 UTC, sijubaker approved these changes

2022-09-22 16:09 UTC, dpathrabe commented
required changes done

2022-09-22 18:54 UTC, ipdksw commented
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-15/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/dd3d5c8bc94d7adca801815f2f1ef0d382d9175f

2022-09-23 12:02 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-63-16/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/dd3d5c8bc94d7adca801815f2f1ef0d382d9175f

2022-09-23 12:56 UTC, dpathrabe commented
Closing this PR and created a new PR #71

2022-09-23 12:56 UTC, closed without merging

2022-09-23 12:56 UTC, dpathrabe commented
Deleting branch