IPDK indirect counter test case automation
ipdk-io/ovs pull request #64
Opened 2022-09-08 05:56 UTC by sjwahub

Signed-off-by: Shujun Wang <shujun.wang@intel.com>

DPDK  indirect counter test case automation

1.  Run test suite log. 
[ptf_tests_run13.log](https://github.com/ipdk-io/ovs/files/9523946/ptf_tests_run13.log)
where you would notice duplicated cases in summary. Actually they're different.  Currently ptf can't differentiate test cases based on json file. In this case, for example, dpdk_l3em_indirect_counter run with pna and psa json files separately.
2. rebuild ovs log 
[Indirect_CT_ovs_build.txt](https://github.com/ipdk-io/ovs/files/9523904/Indirect_CT_ovs_build.txt)

2022-09-08 06:09 UTC, ipdksw commented
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/ddc3097fc4e6f7f0c0e975736a65fea0753f0a7d

2022-09-08 06:34 UTC, ipdksw commented
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/30a292504aa701b2e16f4ff76dccf76f8f69fb75

2022-09-08 07:37 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/1458a68efc7ec8bc9dd80d4481541c32f2188806

2022-09-08 14:40 UTC, 5abeel approved these changes
lgtm

2022-09-09 04:43 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/1458a68efc7ec8bc9dd80d4481541c32f2188806

2022-09-14 06:12 UTC, dkaranjai requested changes

2022-09-14 06:12 UTC, dkaranjai commented on ptf_tests/common/utils/ovsp4ctl_utils.py
> +    :and prepare to restart it.
is this correct description? is it checking for netperf?

2022-09-14 06:12 UTC, dkaranjai commented on ptf_tests/common/utils/ovsp4ctl_utils.py
> +    Args:
please update the function description

2022-09-14 06:12 UTC, dkaranjai commented on ptf_tests/common/utils/test_utils.py
> +    connection.tear_down
tear_down()

2022-09-15 22:15 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-6/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/298bf046a4c59ae6d6d5523564ddc345c9cfa66e

2022-09-19 18:23 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-7/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/298bf046a4c59ae6d6d5523564ddc345c9cfa66e

2022-09-20 04:09 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-8/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/a6eaf330fb12b0025f3038c1275fb34cef0a8abb

2022-09-20 05:19 UTC, sjwahub commented on ptf_tests/common/utils/test_utils.py
> +    connection.tear_down
fixed it.

2022-09-20 07:20 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-9/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/8442b8482f3d019309c0de67a78fd145c71fdc12

2022-09-20 08:01 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-64-10/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/8442b8482f3d019309c0de67a78fd145c71fdc12

2022-09-20 11:08 UTC, dkaranjai approved these changes

2022-09-20 11:08 UTC, merged