Fix for mtu config with tap port test
ipdk-io/ovs pull request #71
Opened 2022-09-23 12:43 UTC by dpathrabe

Signed-off-by: dpathrabe <deepak.p.pathrabe@intel.com>

2022-09-23 12:57 UTC, dpathrabe commented
[mtu_config_tap_fix_exec.log](https://github.com/ipdk-io/ovs/files/9633748/mtu_config_tap_fix_exec.log)
[mtu_config_tap_fix_build.log](https://github.com/ipdk-io/ovs/files/9633750/mtu_config_tap_fix_build.log)
Adding logs

2022-09-23 13:11 UTC, ipdksw commented
Result:FAILURE JenkinsConsole:https://s3.ipdk.io/ovs/PR-71-1/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/30491bdf17f9964c1834e74d624cfa372d7d9b34

2022-09-26 05:33 UTC, dkaranjai requested changes

2022-09-26 05:33 UTC, dkaranjai commented on ptf_tests/tests/mtu_config_test_with_tap.py
> -# Copyright (c) 2022 Intel Corporation.
you need to put these back

2022-09-26 09:40 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-71-2/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/79fde95ec7ddd949a1b58c2ebb22895b87d4f79f

2022-09-26 10:22 UTC, dkaranjai approved these changes

2022-09-30 12:11 UTC, ipdksw commented
Result:ABORTED JenkinsConsole:https://s3.ipdk.io/ovs/PR-71-3/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/79fde95ec7ddd949a1b58c2ebb22895b87d4f79f

2022-10-04 10:56 UTC, dkaranjai approved these changes

2022-10-04 12:03 UTC, sijubaker approved these changes

2022-10-04 13:38 UTC, ipdksw commented
Result:SUCCESS JenkinsConsole:https://s3.ipdk.io/ovs/PR-71-4/index.html GitCommit:https://github.com/ipdk-io/ovs/commits/568a47034ad5cbb33a41bcd9af822d9caf8bc733

2022-10-06 03:03 UTC, merged